from chrisapp.base import ChrisApp


class CustomArgsApp(ChrisApp):
    DESCRIPTION = ''
    TYPE = ''
    TITLE = ''
    LICENSE = ''
    SELFPATH = ''
    SELFEXEC = ''
    EXECSHELL = ''
    OUTPUT_META_DICT = ''
    AUTHORS = ''
    VERSION = ''
    def add_argument_c(self, flag, type=str, optional=True, default='', metavar='', *args, **kwargs):
        """
        Same as self.add_argument, but with some boring defaults
        """
        if not metavar:
            metavar = flag[1].upper()
        metavar = f'<{metavar}>'
        self.add_argument(flag,
                          dest=flag,
                          type=type,
                          default=default,
                          optional=optional,
                          metavar=metavar,
                          *args, **kwargs)
        # don't repeat these options
        if flag not in ['-sourcedir', '-targetdir']:
            self.civet_options.append(flag)

    def add_argless(self, flag, *args, **kwargs):
        """
        Same as self.add_argument_c, intended for boolean CLI options that
        do not need input.
        """
        self.add_argument(flag,
                          dest=flag,
                          type=bool,
                          action='store_true',
                          default=False,
                          optional=True,
                          *args, **kwargs)
        self.civet_options.append(flag)


def add_civet_arguments(p: CustomArgsApp):
    """
    The code for this function is automatically generated by util/help2code.py
    """
    pass
